name: linux-binary

on:
  workflow_call:
    inputs:
      accelerator_type:
        required: true
        type: string
        description: GPU Arch type
      accelerator_version:
        required: true
        type: string
        description: GPU Arch version
      build_name:
        required: true
        type: string
        description: Build name
      builds_on:
        required: true
        type: string
        description: Builds on
      container_image:
        required: true
        type: string
        description: Container image
      package_type:
        required: true
        type: string
        description: Package type
      python_version:
        required: true
        type: string
        description: Python version
      pytorch_extra_install_requirements:
        required: true
        type: string
        description: PyTorch extra install requirements
      runner_prefix: # aka label-type
        required: false
        default: ""
        type: string
        description: prefix for runner label
      test_on:
        required: true
        type: string
        description: Test on
    secrets:
      github-token:
        required: true
        description: Github Token

jobs:
  build:
    uses: ./.github/workflows/_binary-build-linux.yml
    with:
      DESIRED_CUDA: ${{ inputs.accelerator_type }}
      DESIRED_PYTHON: ${{ inputs.python_version }}
      DOCKER_IMAGE: ${{ inputs.container_image }}
      GPU_ARCH_TYPE: ${{ inputs.accelerator_type }}
      GPU_ARCH_VERSION: ${{ inputs.accelerator_version }}
      PACKAGE_TYPE: ${{ inputs.package_type }}
      PYTORCH_ROOT: /pytorch
      build_environment: ${{ inputs.accelerator_type }}
      build_name: build-${{ inputs.build_name }}
      pytorch_extra_install_requirements: ${{ inputs.pytorch_extra_install_requirements }}
      runner_prefix: ${{ inputs.runner_prefix }}
      runs_on: ${{ inputs.builds_on }}
      timeout-minutes: 240
      use_split_build: False
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs:
      - build
    uses: ./.github/workflows/_binary-test-linux.yml
    with:
      build_name: test-${{ inputs.build_name }}
      build_environment: ${{ inputs.accelerator_type }}
      PYTORCH_ROOT: /pytorch
      PACKAGE_TYPE: ${{ inputs.package_type }}
      DESIRED_CUDA: ${{ inputs.accelerator_type }}
      GPU_ARCH_TYPE: ${{ inputs.accelerator_type }}
      GPU_ARCH_VERSION: ${{ inputs.accelerator_version }}
      DOCKER_IMAGE: ${{ inputs.container_image }}
      runs_on: ${{ inputs.test_on }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  upload:
    needs:
      - test
    uses: ./.github/workflows/_binary-upload.yml
    with:
      build_name: upload-${{ inputs.build_name }}
      package_type: ${{ inputs.package_type }}
      GPU_ARCH_TYPE: ${{ inputs.accelerator_type }}
      # TODO: I know this isn't the correct DESIRED_CUDA, need to fix
      DESIRED_CUDA: ${{ inputs.accelerator_type }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
