name: post-trigger-workflow

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-post:
    name: test-post
    uses: ./.github/workflows/post-use-trigger-workflow.yml
    with:
      build-environment: linux
    secrets: inherit
  test-dispatch:
    name: Invoke workflow with inputs
    uses: benc-uk/workflow-dispatch@v1
    with:
      workflow: post_test_dispatch.yml
      inputs: '{ "name": "blah blah"}'
