name: post-test-job-process
on:
  workflow_call:
    inputs:
        workflow_run_id:
          type: string
          description: 'workflow (run) id of the workflow the test is running'
          required: True
        workflow_attempt:
          type: string
          description: 'the workflow (run) attempt'
          required: True
        workflow_name:
          description: 'name of the workflow'
          type: string
          required: True
        job_id:
          type: string
          description: 'the job (run) id for the test'
          required: True
        job_name:
          type: string
          description: 'the job name of the test'
          required: True

jobs:
  process-utilization-logs:
    runs-on: ubuntu-latest
    environment: post-test
    permissions:
      id-token: write
    name: process and upload utilziation logs for ${{ github.event.inputs.workflow_name }}:${{ github.event.inputs.job_name }}, with attempt ${{ github.event.inputs.workflow_attempt}}
    steps:
      - name: Print Inputs
        run: |
          echo "workflow_id: ${{github.event.inputs.workflow_runner_id}}"
          echo "workflow_attempt: ${{github.event.inputs.workflow_attempt}}"
          echo "workflow_Name: ${{github.event.inputs.workflow_name}}"
          echo "job_id: ${{github.event.inputs.job_id}}"
          echo "job_name:  ${{github.event.inputs.job_name}}"
# TODO():add upload utilization tests script
