name: post-use-trigger-workflow

on:
  workflow_call:
    inputs:
      build-environment:
        required: true
        type: string
        description: Top-level label for what's being built/tested.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-process:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Testing
        run: |
          echo "Workflow post-use-trigger-workflow: ${{ github.workflow }}"
