name: post-test-dispatch
on:
  workflow_dispatch:
    inputs:
        name:
          description: 'Your name'
          required: true

jobs:
  post-process:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Version Branch
        uses: actions/checkout@v3
      - name: Testing
        run: |
          echo "Workflow post-test-dispatch: ${{ github.workflow }}"
          echo "Name: ${github.event.inputs.name}"
