name: post-test-dispatch
on:
  pull_request:
  workflow_dispatch:
    inputs:
        name:
          description: 'Your name'
          required: False
          default: "default"
jobs:
  post-process:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "Workflow post-test-dispatch: ${{ github.workflow }}"
