name: post-trigger-workflow

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  test-post:
    name: test-post
    uses: ./.github/workflows/post-use-trigger-workflow.yml
    with:
      build-environment: linux
    secrets: inherit
