name: Unit Tests for script tools
on:
  pull_request:
    paths:
      - 'tools/stats/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  pytest:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: |
          pip install -r tools/stats/script-test-requirements.txt

      - name: Run pytest
        run: |
          pytest tools/stats/
